### ISSUE TITLE
Inconsistency with OneSignal.setNotificationWillShowInForegroundHandler

### ISSUE THREAD

**Issue by ghost** [OneSignal/react-native-onesignal#1265]
**Description:**

I'm trying to implement a feature where we show a custom dialog when the user receives a specific push with the app in focus. Reading the docs I saw [setNotificationWillShowInForegroundHandler](https://documentation.onesignal.com/docs/sdk-notification-event-handlers#foreground-notification-received-event) and the idea was to use it to verify the push notification data and show up this custom dialog while silencing the push with `notificationReceivedEvent.complete()`. 
In theory, it should work perfectly. But, there is a problem:

Sometimes when I receive a notification the callback passed to `setNotificationWillShowInForegroundHandler` gets called and sometimes it doesn't. I could no figure out why this is happening, it seems pretty random. 

**Environment**

1. What version of the OneSignal React-Native SDK are you using? 4.1.1
2. How did you add the SDK to your project? `yarn add ...``

**Steps to Reproduce Issue:**

 1. Install the OneSignal SDK using yarn into your project
 2. Initialize the SDK
 3. Call setNotificationWillShowInForegroundHandler
 4. Receive a push notification
 5. Verify if the callback passed to setNotificationWillShowInForegroundHandler was called

**Anything else:**

Unfortunately, I could only test it on Android. If there is any extra information that I can provide that could help you, please, let me know.

**Comment by jkasten2** [comment]
@emilioheinz Thanks for reporting. Could you share the code of the function you are providing to `setNotificationWillShowInForegroundHandler`? Is there any chance that `notificationReceivedEvent.complete()` might not be getting called?

Could you also let us know what Android versions you have seen this issue on? Any other details on when you notice it is working vs not?

**Comment by ghost** [comment]
@jkasten2 Thanks for the quick response.

The code that I'm trying to use is pretty simple. Just a callback with a `console.log` and a `notificationReceivedEvent.complete()`. I'm assuming that if I cannot see the `console.log` and I can see the notification this callback is not being called.

```js
OneSignal.setNotificationWillShowInForegroundHandler(
  notificationReceivedEvent => {
    console.log('CALLED')

    notificationReceivedEvent.complete()
  }
)
```

About the Android version. I'm using the following configuration on my emulator:
<details>
<summary>Emulator details</summary>
<be>

```
Name: Pixel_2_API_R

CPU/ABI: Google Play Intel Atom (x86)

Path: /Users/emilioheinzmann/.android/avd/Pixel_2_API_R.avd

Target: google_apis_playstore [Google Play] (API level R)

Skin: pixel_2

SD Card: 512M

fastboot.chosenSnapshotFile: 

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: pixel_2

hw.lcd.width: 1080

image.androidVersion.codename: R

hw.initialOrientation: Portrait

image.androidVersion.api: 29

tag.id: google_apis_playstore

hw.mainKeys: no

hw.camera.front: emulated

avd.ini.displayname: Pixel 2 API R

hw.gpu.mode: auto

hw.ramSize: 1536

PlayStore.enabled: true

fastboot.forceColdBoot: no

hw.cpu.ncore: 4

hw.keyboard: yes

hw.sensors.proximity: yes

hw.dPad: no

hw.lcd.height: 1920

vm.heapSize: 256

skin.dynamic: yes

hw.device.manufacturer: Google

hw.gps: yes

hw.audioInput: yes

image.sysdir.1: system-images/android-R/google_apis_playstore/x86/

showDeviceFrame: yes

hw.camera.back: virtualscene

AvdId: Pixel_2_API_R

hw.lcd.density: 420

hw.arc: false

hw.device.hash2: MD5:55acbc835978f326788ed66a5cd4c9a7

fastboot.forceChosenSnapshotBoot: no

fastboot.forceFastBoot: yes

hw.trackBall: no

hw.battery: yes

hw.sdCard: yes

tag.display: Google Play

runtime.network.latency: none

disk.dataPartition.size: 6442450944

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes
```

</details>

**Comment by ghost** [comment]
Any updates on this?

**Comment by nan-li** [comment]
Hi @emilioheinz it has been addressed and will be available in the next `react-native-onesignal` release.

**Comment by ghost** [comment]
Nice, thank you.

**Comment by MustafaAlsihati** [comment]
I have the same exact issue with `setNotificationWillShowInForegroundHandler` being called sometimes and sometimes not even when notification appear on the device notifications. 

Like you said it's random, I couldn't figure out how and why it does this. And we realised it happens on iOS and Android (both GMS and HMS). We use OneSignal service to receive online orders to the devices so it's causing us major issues unfortunately :(

Hope it gets fixed soon.

I'm using `react-native-onesignal: 4.2.0`.

**Comment by ghost** [comment]
@MustafaAlsihati as @nan-li said it should be fixed in the latest version (4.3.0). I've not tested it yet but if have the time it would be a good try.

**Comment by RigottiG** [comment]
It looks like is working fine in the latest version `react-native-onesignal: 4.3.0` and `react-native: 0.65.1`

**Comment by MustafaAlsihati** [comment]
Problem still occur in `react-native-onesignal: 4.3.0`, it still occur randomly like I said before for both iOS and Android (GMS & HMS).

**Comment by ghost** [comment]
@MustafaAlsihati Are you in the latest RN version?

**Comment by nan-li** [comment]
@MustafaAlsihati are you still having this issue?

**Comment by MustafaAlsihati** [comment]
Yes I do still have this issue, I use `react-native": "0.64.2`, I updated to RN to `0.65.1` and test it on Android but the issue still exist.
Not sure why and how it happens, it's really weird.

**Comment by sweatherall** [comment]
Issue still exists on RN version: 0.66.3, react-native-onesignal: 4.3.3 - left comment [here](https://github.com/OneSignal/react-native-onesignal/issues/1210) to get this issue reopened.
@MustafaAlsihati @nan-li was there any resolution for you all?
