### ISSUE TITLE
Application crashes due to one signal when run on Android 12 device

### ISSUE THREAD

**Issue by dbilgin** [OneSignal/react-native-onesignal#1310]
**Description:**

Android 12 recently made it mandatory to use `FLAG_IMMUTABLE`  or `FLAG_MUTABLE`, this makes the application crash as soon as it's opened.

**Environment**

react-native-onesignal version: 4.3.1
added to the project with yarn

**Steps to Reproduce Issue:**

1. Install one signal
2. Initialise onesignal in react native
3. Run the app on an Android 12 device

**Anything else:**

(crash stacktraces, as well as any other information here)
```
Process: , PID: 19559
    java.lang.IllegalArgumentException: : Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:273)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:151)
        at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:171)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:102)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
```

**Comment by rgomezp** [comment]
Howdy,
I'm not seeing OneSignal anywhere in the stack trace. Can you please include more of the log or perhaps explain a bit more why you think this is a OneSignal-related issue?

Cheers

**Comment by dbilgin** [comment]
@rgomezp thanks for your reply, well I don't call PendingIntent anywhere on the native side and it works fine when I remove only the onesignal sdk from package.json

**Comment by rgomezp** [comment]
What device are you running this on?

**Comment by dbilgin** [comment]
I've tried running it on an emulator with Android 12 installed and my Pixel 5 which also has Android 12 installed. It works fine for anything below Android 12 so far.
One more thing I realised recently, I tried creating a pure Android project and adding your [native Android sdk there](https://documentation.onesignal.com/docs/android-sdk-setup) and I faced the same issue. It crashes on application start.

**Comment by nan-li** [comment]
Stack trace is same as https://github.com/OneSignal/OneSignal-Android-SDK/issues/1442.
The [fix](https://github.com/OneSignal/OneSignal-Android-SDK/pull/1477) is merged but not released yet.

> In the meantime you can use this version in your app by simply adding it to your `app/build.gradle`.
> ```
> api 'androidx.work:work-runtime:2.7.0-rc01'
> ```

**Comment by dbilgin** [comment]
Thanks @nan-li! I guess I can close this then. The temporary fix seems to work as well.

**Comment by dbilgin** [comment]
Hi again @rgomezp, this issue seems to still be there with version 4.3.1 even though there has been a [release](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.6.2) on the android sdk if I am not mistaken.

**Comment by dbilgin** [comment]
Created a PR for this [here](https://github.com/OneSignal/react-native-onesignal/pull/1315/files). Seems to resolve it for me at least.

**Comment by jkasten2** [comment]
@dbilgin This is now fixed in the [4.3.2 release](https://github.com/OneSignal/react-native-onesignal/releases/tag/4.3.2)

**Comment by kdqtech** [comment]
HI team , I have followed this all the steps but still this is not resolved for me with latest library version

**Comment by raahimkhan** [comment]
Getting this too.
