### ISSUE TITLE
Execution failed for task ':app:checkDebugAarMetadata'.

### ISSUE THREAD

**Issue by sumanbhattarai** [OneSignal/react-native-onesignal#1318]
**Description:**

I created a new react native application and installed react-native-one-signal. I am getting a build error on android as soon as I installed react-native-one-signal.
I am getting following error while building an app on android:

```
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.work:work-runtime:2.7.0.
     AAR metadata file: /Users/sumanbhattarai/.gradle/caches/transforms-3/ac32b6abd74d5ceefc471e061744b632/transformed/work-runtime-2.7.0/META-INF/com/android/build/gradle/aar-metadata.properties.

```

**Environment**

 ```
"react": "17.0.2",
"react-native": "0.66.2",
"react-native-onesignal": "^4.3.2"
```

**Steps to Reproduce Issue:**

1. Create a new project using ``` npx react-native init DempApp --template react-native-template-typescript``` .
2. Install one signal using ``` yarn add react-native-onesignal```
3.  Run on android phone. ``` npx react-native run-android```

**Comment by ROG3R-DEV** [comment]
@sumanbhattarai on android/build.gradle

change:

compileSdkVersion = 31

```
buildscript {
    ext {
        compileSdkVersion = 31
       ....
```

**Comment by sweatherall** [comment]
I can confirm @ROG3R-DEV solution works - I was running into the exact same problem, and updating `compileSdkVersion` to `31`, as the error message suggests, allows for a successful build.

**Comment by Ricool06** [comment]
I'm also getting this issue, 4.3.1 builds fine (but ID verification is not working). 4.3.2 is where this issue is introduced.
I can't change `build.gradle` as @ROG3R-DEV has suggested as I am using expo with a managed workflow.

Does anyone have an alternative workaround so I can use ID verification?

**Comment by Summys** [comment]
If you don't want to upgrade to sdk 31, add in `android/app/build.gradle` 
```
android {
    ...
    defaultConfig {
        ...
        configurations.all {
            resolutionStrategy { force 'androidx.work:work-runtime:2.6.0' }
        }
    }
}
```

**Comment by nan-li** [comment]
For some background, we made [this change](https://github.com/OneSignal/OneSignal-Android-SDK/pull/1477/commits/51574b69124930a2a90867f3b89e8413f3414ad5) for apps that set their `compileSdkVersion` to 31. 

@Ricool06, thanks for bringing up a good point about the managed workflow as it appears the latest Expo SDK targets Android 30.

**Comment by Ricool06** [comment]
> If you don't want to upgrade to sdk 31, add in `android/app/build.gradle` 
> ```
> android {
>     ...
>     defaultConfig {
>         ...
>         configurations.all {
>             resolutionStrategy { force 'androidx.work:work-runtime:2.6.0' }
>         }
>     }
> }
> ```

I can't upgrade to sdk 31 without ejecting, which I also cannot do in my situation.

@nan-li glad to be helping. 😊 Is there a resolution or workaround to this we can think of?

**Comment by Saad-Bashar** [comment]
Having the same problem with onesignal 4.3.3 :( I am using expo unimodules and when I upgraded to 31 the expo packages can not run.

Update: By using this, I could run the app. However not sure if its a good idea. 
```
android {
    ...
    defaultConfig {
        ...
        configurations.all {
            resolutionStrategy { force 'androidx.work:work-runtime:2.6.0' }
        }
    }
}
```

**Comment by Svarto** [comment]
same issue, glad it is identified why it happens. I downgraded for now, but hope it will be addressed when expo SDK 44 comes out...

**Comment by jkasten2** [comment]
This issue has been addressed in [OneSignal-Gradle-Plugin 0.14.0](https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.14.0). This version should automatically be picked up if you do a clean build.

**Comment by Saad-Bashar** [comment]
@jkasten2 , I am doing ./gradlw clean and trying back again. Still getting the same error somehow? Am I doing it right?

**Comment by Ricool06** [comment]
So for anyone still struggling with this who can't eject or update to the version @jkasten2 mentioned, here is a workaround.
Add this to your `app.config.js`:

```javascript
const newResolutionStrategyGradle = `
configurations.all {
    resolutionStrategy {
        force 'androidx.work:work-runtime:2.6.0'
    }
}`;

const withWorkingWorkRuntimeVersion = (config, _props) => {
  return withAppBuildGradle(config, newConfig => {
    newConfig.modResults.contents = `${newResolutionStrategyGradle.trimStart()}\n\n${
      newConfig.modResults.contents
    }`;

    return newConfig;
  });
};
```

then return your config where you usually would with
```javascript
return withWorkingWorkRuntimeVersion(config);
```

EDIT: this assumes you are using expo!

**Comment by jkasten2** [comment]
The available version list of the `onesignal-gradle-plugin` (OneSignal-Gradle-Plugin) hasn't been updated with 0.14.0 yet:
   - https://plugins.gradle.org/m2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml

I am not sure exactly when Gradle's plugin portal will refresh the latest version list but I would expect in the next 24 hours.

**Comment by huurray** [comment]
> If you don't want to upgrade to sdk 31, add in `android/app/build.gradle`
> 
> ```
> android {
>     ...
>     defaultConfig {
>         ...
>         configurations.all {
>             resolutionStrategy { force 'androidx.work:work-runtime:2.6.0' }
>         }
>     }
> }
> ```

this works for me!!

**Comment by scooterthedev** [comment]
> If you don't want to upgrade to sdk 31, add in `android/app/build.gradle`
> 
> ```
> android {
>     ...
>     defaultConfig {
>         ...
>         configurations.all {
>             resolutionStrategy { force 'androidx.work:work-runtime:2.6.0' }
>         }
>     }
> }
> ```

Thank you so much @Summys! This is just what I needed to fix my problem.

**Comment by phamhieu1412** [comment]
> If you don't want to upgrade to sdk 31, add in `android/app/build.gradle`
> 
> ```
> android {
>     ...
>     defaultConfig {
>         ...
>         configurations.all {
>             resolutionStrategy { force 'androidx.work:work-runtime:2.6.0' }
>         }
>     }
> }
> ```

worked for me 

buildToolsVersion = "30.0.2"
minSdkVersion = 21
compileSdkVersion = 30
targetSdkVersion = 30
ndkVersion = "21.4.7075529"

rn: 0.66.4

**Comment by Luxiyaya** [comment]
@Summys Thank you You solved my problem

```
android {
    ...
    defaultConfig {
        ...
        configurations.all {
            resolutionStrategy { force 'androidx.work:work-runtime:2.6.0' }
        }
    }
}

```

**Comment by pmdev71** [comment]
If you don't want to upgrade to sdk 31, add in android/app/build.gradle

android {
    ...
    defaultConfig {
        ...
        configurations.all {
            resolutionStrategy { force 'androidx.work:work-runtime:2.6.0' }
        }
    }
}

**Comment by Dcrosssensei** [comment]
worked for me + 

buildToolsVersion = "29.0.3"
minSdkVersion = 21
compileSdkVersion = 30
targetSdkVersion = 30

> If you don't want to upgrade to sdk 31, add in `android/app/build.gradle`
> 
> ```
> android {
>     ...
>     defaultConfig {
>         ...
>         configurations.all {
>             resolutionStrategy { force 'androidx.work:work-runtime:2.6.0' }
>         }
>     }
> }
> ```

**Comment by itshash01** [comment]
I just had the same issue, so its better to go to build.gradle and check targetSDK and compileSDK then we will notice a kind of warning asking us to update...we are 13th DECEMBER 2022 I update mine to 33 which were from the beginning 32.

**Comment by itshash01** [comment]
> worked for me +
> 
> buildToolsVersion = "29.0.3" minSdkVersion = 21 compileSdkVersion = 30 targetSdkVersion = 30
> 
> > If you don't want to upgrade to sdk 31, add in `android/app/build.gradle`
> > ```
> > android {
> >     ...
> >     defaultConfig {
> >         ...
> >         configurations.all {
> >             resolutionStrategy { force 'androidx.work:work-runtime:2.6.0' }
> >         }
> >     }
> > }
> > ```

yeah targetSDK and compileSDK must be upgraded(id did it to 33)

**Comment by OFD16** [comment]
on this route: ```android -> build.gradle``` 
add this part ```androidXBrowser = "1.5.0"```
```
buildscript {
    ext {
        // ...
        androidXBrowser = "1.5.0"
```
[resource1](https://github.com/proyecto26/react-native-inappbrowser/issues/423)
[resource2](https://github.com/proyecto26/react-native-inappbrowser/issues/423)

this solved my problem

**Comment by subrat71** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform react-android-0.76.2-debug.aar (com.facebook.react:react-android:0.76.2) to match attributes {artifactType=android-aar-metadata, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\shish\.gradle\caches\modules-2\files-2.1\com.facebook.react\react-android\0.76.2\5750f3d5ebde84a5319477b6f90082ecac141b47\react-android-0.76.2-debug.aar.
         > Java heap space

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform react-android-0.76.2-debug.aar (com.facebook.react:react-android:0.76.2) to match attributes {artifactType=android-aar-metadata, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\shish\.gradle\caches\modules-2\files-2.1\com.facebook.react\react-android\0.76.2\5750f3d5ebde84a5319477b6f90082ecac141b47\react-android-0.76.2-debug.aar.
         > Java heap space

   > Failed to transform react-android-0.76.2-debug.aar (com.facebook.react:react-android:0.76.2) to match attributes {artifactType=android-aar-metadata, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\shish\.gradle\caches\modules-2\files-2.1\com.facebook.react\react-android\0.76.2\5750f3d5ebde84a5319477b6f90082ecac141b47\react-android-0.76.2-debug.aar.
         > Java heap space

lease, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\shish\.gradle\caches\modules-2\files-2.1\com.facebook.react\react-android\0.76.2\5750f3d5ebde84a5319477b6f90082ecac141b47\react-android-0.76.2-debug.aar.
         > Java heap space

         > Java heap space
         
         

>  buildToolsVersion = "35.0.0"
        minSdkVersion = 24
        compileSdkVersion = 35
        targetSdkVersion = 34
        ndkVersion = "26.1.10909125"
        kotlinVersion = "1.9.24"

"react-native": "^0.76.2"

**Comment by souravm01** [comment]
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > An issue was found when checking AAR metadata:

       1.  Dependency 'androidx.webkit:webkit:1.14.0' requires Android Gradle plugin 8.1.1 or higher.

           This build currently uses Android Gradle plugin 7.4.2.

**Comment by yisi89** [comment]
> Execution failed for task ':app:checkDebugAarMetadata'.
> 
> > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
> > An issue was found when checking AAR metadata:
> 
> ```
>    1.  Dependency 'androidx.webkit:webkit:1.14.0' requires Android Gradle plugin 8.1.1 or higher.
> 
>        This build currently uses Android Gradle plugin 7.4.2.
> ```

I faced the same issue and managed to resolved by putting the following block under app level build.gradle file under the defaultConfig section:

 defaultConfig {
    configurations.all {
                resolutionStrategy { force 'androidx.webkit:webkit:1.13.0' }
            }
    ....
}

You can try gradle clean to see if it works.

**Comment by MohitNarkhede** [comment]
> Execution failed for task ':app:checkDebugAarMetadata'.
> 
> > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
> > An issue was found when checking AAR metadata:
> 
> ```
>    1.  Dependency 'androidx.webkit:webkit:1.14.0' requires Android Gradle plugin 8.1.1 or higher.
> 
>        This build currently uses Android Gradle plugin 7.4.2.
> ```

how did you solved this?
@souravm01
