### ISSUE TITLE
idsAvailable() does not call callback if no pushToken.

### ISSUE THREAD

**Issue by seokgyo** [OneSignal/react-native-onesignal#14]
The current implementation does not call callback if there's no pushToken in idsAvailable().
But to be consistent w/ original behaviour it seems better to callback w/ null pushToken. On client there's no way to detect what's happening.

What do you think?
Thanks.

**Comment by micksabox** [comment]
+1
@seokgyo do you mean when the user declines to allow push notifications? I'm not sure if there is a way to detect this now, but it would be nice to know this. Passing null as a pushToken would be a good way to do it.

**Comment by seokgyo** [comment]
The following is the current implementation for ios:

`
RCT_EXPORT_METHOD(idsAvailable:(RCTResponseSenderBlock)callback) {
    [oneSignal IdsAvailable:^(NSString* userId, NSString* pushToken) {
        NSLog(@"UserId:%@", userId);
        if (pushToken != nil) {
            NSLog(@"pushToken:%@", pushToken);
            NSDictionary *value = @{
                                    @"pushToken": pushToken,
                                    @"playerId" : userId
                                    };
            callback(@[value]);
        } else {
            NSLog(@"Cannot Get Push Token");
        }
    }];
}
`

If pushToken is null, callback is not called. And the caller could not know what's going on. I don't know if there're some reasons for this. But in my opinion, callback should be called whether pushToke is null or not.

BTW pushToken is always null in iOS simulator.

**Comment by JonathanWi** [comment]
+1 for this feature: If the user register later during the process, I need to listen to the callback of his press (accept/decline) in order to move on to the next page.

**Comment by avishayil** [comment]
Hi, I won't be available on the next month to add new features. If you have any idea for a PR, i'll be happy to review it.
Hopefully after mid May i'll be back to add new features to this library.

I'll add this to the TODO list.

**Comment by avishayil** [comment]
Update to the latest package version, I fixed it and the callback is working in both iOS and Android.

The following code checks if the ids object is empty, if it is, console log "No Ids".

``` javascript
OneSignal.idsAvailable((ids) => {
    if (Object.keys(ids).length === 0 && ids.constructor === Object) {
        console.log("No Ids");
    }
});
```

Please re-open the issue if any problem occurs.

Thanks!

**Comment by JonathanWi** [comment]
Hey @avishayil I'm still not sure the case is closed:

If using `OneSignal.registerForPushNotifications();`, how do I know if a button has been pressed? `OneSignal.addEventListener('ids', (device) => { ...})` allows me to know if the user pressed allow, but I have no way to know if the user declined the prompt...

Any idea on how to do that? I'd like to move the user to the next page after the selection has been made, but I'm only able to do that for the users that grant permissions.

Cheers!
