### ISSUE TITLE
[Bug]: Termination Reason: DYLD 1 Library missing Library not loaded: @rpath/OneSignalExtension.framework/OneSignalExtension

### ISSUE THREAD

**Issue by Bayramito** [OneSignal/react-native-onesignal#1500]
### What happened?

```
Termination Reason: DYLD 1 Library missing
Library not loaded: @rpath/OneSignalExtension.framework/OneSignalExtension
```

i get this error when i try to build with XCode, building finishes but app crash on startup with this error.

![Ekran Resmi 2023-03-18 11 18 43](https://user-images.githubusercontent.com/44513402/226096873-4eadefa4-3936-4413-9be4-d43d158580d8.png)
If i add them like that it was working before but now i throws this

![Ekran Resmi 2023-03-18 11 19 31](https://user-images.githubusercontent.com/44513402/226096905-aa5d5c32-c496-4c6a-825e-6e5089724a54.png)

### Steps to reproduce?

```Markdown
Just install the latest version
```

### What did you expect to happen?

App crashed at startup

### React Native OneSignal SDK version

4.5.1

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
dyld[36000]: Library not loaded: @rpath/OneSignalExtension.framework/OneSignalExtension
  Referenced from: <73267F14-3268-3859-8C8A-F520871A425C> /Users/bayram/Library/Developer/CoreSimulator/Devices/7A5132B8-C78D-4552-A493-6A8B5283B2DF/data/Containers/Bundle/Application/D48308EF-DDF5-400A-B3C2-39FA04812850/omuzreact.app/omuzreact
  Reason: tried: '/Users/bayram/Library/Developer/Xcode/DerivedData/omuzreact-duyekhofqkcjgacibvlgueczygxi/Build/Products/Debug-iphonesimulator/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/Users/bayram/Library/Developer/CoreSimulator/Devices/7A5132B8-C78D-4552-A493-6A8B5283B2DF/data/Containers/Bundle/Application/D48308EF-DDF5-400A-B3C2-39FA04812850/omuzreact.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/Users/bayram/Library/Developer/CoreSimulator/Devices/7A5132B8-C78D-4552-A493-6A8B5283B2DF/data/Containers/Bundle/Application/D48308EF-DDF5-400A-B3C2-39FA04812850/omuzreact.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/Users/bayram/Library/Developer/CoreSimulator/Devices/7A5132B8-C78D-4552-A493-6A8B5283B2DF/data/Containers/Bundle/Application/D48308EF-DDF5-400A-B3C2-39FA04812850/omuzreact.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/Users/bayram/Library/Developer/CoreSimulator/Devices/7A5132B8-C78D-4552-A493-6A8B5283B2DF/data/Containers/Bundle/Application/D48308EF-DDF5-400A-B3C2-39FA04812850/omuzreact.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/Users/bayram/Library/Developer/CoreSimulator/Devices/7A5132B8-C78D-4552-A493-6A8B5283B2DF/data/Containers/Bundle/Application/D48308EF-DDF5-400A-B3C2-39FA04812850/omuzreact.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/Users/bayram/Library/Developer/CoreSimulator/Devices/7A5132B8-C78D-4552-A493-6A8B5283B2DF/data/Containers/Bundle/Application/D48308EF-DDF5-400A-B3C2-39FA04812850/omuzreact.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2)
dyld[36001]: Library not loaded: @rpath/OneSignalExtension.framework/OneSignalExtension
  Referenced from: <73267F14-3268-3859-8C8A-F520871A425C> /Users/bayram/Library/Developer/CoreSimulator/Devices/7A5132B8-C78D-4552-A493-6A8B5283B2DF/data/Containers/Bundle/Application/D48308EF-DDF5-400A-B3C2-39FA04812850/omuzreact.app/omuzreact
  Reason: tried: '/Users/bayram/Library/Developer/Xcode/DerivedData/omuzreact-duyekhofqkcjgacibvlgueczygxi/Build/Products/Debug-iphonesimulator/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/Users/bayram/Library/Developer/CoreSimulator/Devices/7A5132B8-C78D-4552-A493-6A8B5283B2DF/data/Containers/Bundle/Application/D48308EF-DDF5-400A-B3C2-39FA04812850/omuzreact.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/Users/bayram/Library/Developer/CoreSimulator/Devices/7A5132B8-C78D-4552-A493-6A8B5283B2DF/data/Containers/Bundle/Application/D48308EF-DDF5-400A-B3C2-39FA04812850/omuzreact.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/Users/bayram/Library/Developer/CoreSimulator/Devices/7A5132B8-C78D-4552-A493-6A8B5283B2DF/data/Containers/Bundle/Application/D48308EF-DDF5-400A-B3C2-39FA04812850/omuzreact.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/Users/bayram/Library/Developer/CoreSimulator/Devices/7A5132B8-C78D-4552-A493-6A8B5283B2DF/data/Containers/Bundle/Application/D48308EF-DDF5-400A-B3C2-39FA04812850/omuzreact.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/Users/bayram/Library/Developer/CoreSimulator/Devices/7A5132B8-C78D-4552-A493-6A8B5283B2DF/data/Containers/Bundle/Application/D48308EF-DDF5-400A-B3C2-39FA04812850/omuzreact.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/Users/bayram/Library/Developer/CoreSimulator/Devices/7A5132B8-C78D-4552-A493-6A8B5283B2DF/data/Containers/Bundle/Application/D48308EF-DDF5-400A-B3C2-39FA04812850/omuzreact.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Gfr1992** [comment]
Hello, do you have any update on this?

**Comment by Bayramito** [comment]
Fixed with latest version

**Comment by erickgtzh** [comment]
> 
how??
updated it but I'm still getting the same issue :/ (v4.5.1)

**Comment by erickgtzh** [comment]
> Fixed with latest version

how??
updated it but I'm still getting the same issue :/ (v4.5.1)

**Comment by pierroo** [comment]
I am confused too; last version is 4.5.1 and was pushed last week; was there a new version since @Bayramito ?

**Comment by Bayramito** [comment]
On me, i am using react-native 0.71.4 (latest) on my project 

and this is the onesignal config in my podfile...

```
target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
end

```

this is the onesignal version....

`
"react-native-onesignal": "^4.5.1",
`

and i did not added any framework or something manually from xcode.

and it's working perfectly. I just cleaned my pod cache,  as well as DerivedData, maybe you need to perform these as well

**Comment by emawby** [comment]
This is likely a duplicate of https://github.com/OneSignal/react-native-onesignal/issues/1459. There is discussion of fixes in that thread that could help!
