### ISSUE TITLE
[Bug]: NullPointer on initWithContext on Android

### ISSUE THREAD

**Issue by arthurgeron-work** [OneSignal/react-native-onesignal#1587]
### What happened?

Some users are experiencing crashes right after splash screen; Android's diagnostics are pointing to oneSignal

### Steps to reproduce?

```Markdown
It seems just having a default OneSignal v5 setup will cause crashes on some devices, it seems to affect Xiaomi and Motorola devices running android 13+
```

### What did you expect to happen?

Should not Crash

### React Native OneSignal SDK version

Release 5

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
First stacktrace:

Exception java.lang.RuntimeException:
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7232)
  at android.app.ActivityThread.-$$Nest$mhandleBindApplication
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2241)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:211)
  at android.os.Looper.loop (Looper.java:300)
  at android.app.ActivityThread.main (ActivityThread.java:8395)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:559)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:954)
Caused by java.lang.reflect.InvocationTargetException:
  at java.lang.reflect.Constructor.newInstance0
  at java.lang.reflect.Constructor.newInstance (Constructor.java:343)
  at com.onesignal.common.services.ServiceRegistrationReflection.resolve (ServiceRegistration.kt:238)
  at com.onesignal.common.services.ServiceProvider.getServiceOrNull (ServiceProvider.kt:51)
  at com.onesignal.common.services.ServiceProvider.getService (ServiceProvider.kt:6)
  at com.onesignal.internal.OneSignalImp.initWithContext (OneSignalImp.kt:76)
  at com.onesignal.OneSignal.initWithContext (OneSignal.kt:1)
  at com.tradersclub.tc.MainApplication.onCreate (MainApplication.java:25)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1289)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7226)
Caused by java.lang.NullPointerException:
  at com.onesignal.core.internal.application.impl.ApplicationService.getAppContext (ApplicationService.kt:3)
  at com.onesignal.core.internal.preferences.impl.PreferencesService.getSharedPrefsByName (PreferencesService.kt:4)
  at com.onesignal.core.internal.preferences.impl.PreferencesService.get (PreferencesService.kt:38)
  at com.onesignal.core.internal.preferences.impl.PreferencesService.getString (PreferencesService.kt:13)
  at com.onesignal.common.modeling.ModelStore.load (ModelStore.kt:29)
  at com.onesignal.common.modeling.SimpleModelStore.<init> (SimpleModelStore.kt:4)
  at com.onesignal.core.internal.config.ConfigModelStore.<init> (ConfigModelStore.kt:12)
```

Second stacktrace:
```
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7619)
  at android.app.ActivityThread.-$$Nest$mhandleBindApplication
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2400)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8757)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
Caused by java.lang.NullPointerException:
  at com.onesignal.core.internal.application.impl.ApplicationService.getAppContext (ApplicationService.kt:3)
  at com.onesignal.core.internal.device.impl.DeviceService.packageInstalledAndEnabled (DeviceService.kt:3)
  at com.onesignal.core.internal.device.impl.DeviceService.isGMSInstalledAndEnabled (DeviceService.kt:3)
  at com.onesignal.core.internal.device.impl.DeviceService.supportsGooglePush (DeviceService.kt:9)
  at com.onesignal.core.internal.device.impl.DeviceService.getDeviceType (DeviceService.kt:10)
  at com.onesignal.core.internal.device.impl.DeviceService.isAndroidDeviceType (DeviceService.kt:1)
  at com.onesignal.location.LocationModule$register$1.invoke (LocationModule.kt:3)
  at com.onesignal.location.LocationModule$register$1.invoke (LocationModule.kt:1)
  at com.onesignal.common.services.ServiceRegistrationLambda.resolve (ServiceRegistration.kt:13)
  at com.onesignal.common.services.ServiceProvider.getServiceOrNull (ServiceProvider.kt:51)
  at com.onesignal.common.services.ServiceProvider.getService (ServiceProvider.kt:6)
  at com.onesignal.common.services.ServiceRegistrationReflection.resolve (ServiceRegistration.kt:208)
  at com.onesignal.common.services.ServiceProvider.getServiceOrNull (ServiceProvider.kt:51)
  at com.onesignal.common.services.ServiceProvider.getService (ServiceProvider.kt:6)
  at com.onesignal.common.services.ServiceRegistrationReflection.resolve (ServiceRegistration.kt:208)
  at com.onesignal.common.services.ServiceProvider.getServiceOrNull (ServiceProvider.kt:51)
  at com.onesignal.common.services.ServiceProvider.getService (ServiceProvider.kt:6)
  at com.onesignal.internal.OneSignalImp.initWithContext (OneSignalImp.kt:233)
  at com.onesignal.OneSignal.initWithContext (OneSignal.kt:1)
  at com.tradersclub.tc.MainApplication.onCreate (MainApplication.java:25)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1266)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7614)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

<!-- probot = {"onesignal-probot":{"response_time_in_business_days":1}} -->

**Comment by caghp94** [comment]
any short term workaround for this?

**Comment by emawby** [comment]
@arthurgeron-work Are you able to reproduce this issue on SDK 5.0.2?

**Comment by arthurgeron-work** [comment]
> @arthurgeron-work Are you able to reproduce this issue on SDK 5.0.2?

Only some employees have Androids that reproduce this crash, I've built a version with 5.0.2 and asked them to test it, though here it's a national holiday today we might only get a reply Friday, I'll post here as soon as I get some feedback.

**Comment by arthurgeron-work** [comment]
> @arthurgeron-work Are you able to reproduce this issue on SDK 5.0.2?

I've confirmed that the issue persists on SDK 5.0.2.

**Comment by emawby** [comment]
Thank you for your reply. I am not sure if the issue is related to those others since those are not null pointer exceptions. 
I am thinking this is either:
1. [The context](https://github.com/OneSignal/react-native-onesignal/blob/868e5a7f498ff846de0bead34bfc44e7dad5eaf0/android/src/main/java/com/onesignal/rnonesignalandroid/RNOneSignal.java#L234) being sent to the Android Native SDK is null.
2. There is some kind of ordering issue in init with service registration where the DeviceService is being initialized prior to the ApplicationService, but depends on something from the ApplicationService that hasn't been setup yet.

I am investigating which of these issues it is.

**Comment by emawby** [comment]
@arthurgeron-work If you are able to get verbose logs when reproducing the crash that would be helpful! In particular I would like to know if `ApplicationService.init:` is somewhere in then logs.

**Comment by arthurgeron-work** [comment]
@emawby  Thank you for looking into this, unfortunately this exception is hard to reproduce locally

I've found some related failure/error, here's the stacktrace:
```
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7619)
  at android.app.ActivityThread.-$$Nest$mhandleBindApplication
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2400)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8757)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
Caused by java.lang.NullPointerException:
  at com.onesignal.core.internal.application.impl.ApplicationService.getAppContext (ApplicationService.kt:3)
  at com.onesignal.core.internal.device.impl.DeviceService.packageInstalledAndEnabled (DeviceService.kt:3)
  at com.onesignal.core.internal.device.impl.DeviceService.isGMSInstalledAndEnabled (DeviceService.kt:3)
  at com.onesignal.core.internal.device.impl.DeviceService.supportsGooglePush (DeviceService.kt:9)
  at com.onesignal.core.internal.device.impl.DeviceService.getDeviceType (DeviceService.kt:10)
  at com.onesignal.core.internal.device.impl.DeviceService.isAndroidDeviceType (DeviceService.kt:1)
  at com.onesignal.location.LocationModule$register$1.invoke (LocationModule.kt:3)
  at com.onesignal.location.LocationModule$register$1.invoke (LocationModule.kt:1)
  at com.onesignal.common.services.ServiceRegistrationLambda.resolve (ServiceRegistration.kt:13)
  at com.onesignal.common.services.ServiceProvider.getServiceOrNull (ServiceProvider.kt:51)
  at com.onesignal.common.services.ServiceProvider.getService (ServiceProvider.kt:6)
  at com.onesignal.common.services.ServiceRegistrationReflection.resolve (ServiceRegistration.kt:208)
  at com.onesignal.common.services.ServiceProvider.getServiceOrNull (ServiceProvider.kt:51)
  at com.onesignal.common.services.ServiceProvider.getService (ServiceProvider.kt:6)
  at com.onesignal.common.services.ServiceRegistrationReflection.resolve (ServiceRegistration.kt:208)
  at com.onesignal.common.services.ServiceProvider.getServiceOrNull (ServiceProvider.kt:51)
  at com.onesignal.common.services.ServiceProvider.getService (ServiceProvider.kt:6)
  at com.onesignal.internal.OneSignalImp.initWithContext (OneSignalImp.kt:233)
  at com.onesignal.OneSignal.initWithContext (OneSignal.kt:1)
  at com.tradersclub.tc.MainApplication.onCreate (MainApplication.java:25)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1266)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7614)
```

No logs about ApplicationService.init.

**Comment by emawby** [comment]
@arthurgeron-work When/where do you initialize OneSignal in the lifecycle of your application? Also I am seeing that the stacktrace has `initWithContext` called from `MainApplication.onCreate()`. Is your app making that call explicitly?

**Comment by arthurgeron-work** [comment]
> @arthurgeron-work When/where do you initialize OneSignal in the lifecycle of your application? Also I am seeing that the stacktrace has `initWithContext` called from `MainApplication.onCreate()`. Is your app making that call explicitly?

I followed the native's SDK  [android setup documentation](https://documentation.onesignal.com/docs/react-native-sdk-setup#android-devices), which [instructs](https://documentation.onesignal.com/docs/android-sdk-setup#2-initialization) to manually place "initWithContext" inside `onCreate` method.

I'm also initializing it in JS (only once per app execution), as instructed to by the [docs](https://documentation.onesignal.com/docs/react-native-sdk-setup#2-initialization).

It functions normally for most devices, there's a very low percentage ( e.g. Moto G) which are reporting those exceptions to Android Vitals

**Comment by emawby** [comment]
I see. You do not need to follow the android native setup and I am thinking that it might be causing the issue. The react-native initialize alone is sufficient!

**Comment by markui** [comment]
@emawby 

Hello, it states https://documentation.onesignal.com/docs/react-native-sdk-setup here in Android devices, that you should follow android sdk setup steps. What is true?

**Comment by KaizerDmitry** [comment]
Hello @arthurgeron-work. Any progress with this one? Workaround maybe?
I have same problem with my Android device. 
It's unfortunate that we have also only one Android device and issue is there

**Comment by arthurgeron-work** [comment]
> Hello @arthurgeron-work. Any progress with this one? Workaround maybe?
> 
> I have same problem with my Android device. 
> 
> It's unfortunate that we have also only one Android device and issue is there

I had to:
- Not call product more than once in parallel (await for previous promise/loading state)
- Not call initWithContext inside JS context 

I believe the latter will help with this specific bug, but many others were recently fixed in a recent OneSignal's Android SDK update. So you might just need to test it again.

**Comment by nan-li** [comment]
We have updated the [react native setup instructions](https://documentation.onesignal.com/docs/react-native-sdk-setup#android-devices) to only keep any Android instructions that are still relevant.

Please let us know if this issue reported still occurs.

**Comment by nan-li** [comment]
Hi @arthurgeron-work,

I am investigating reports of this crash from other users still reporting this happening.

> Not call initWithContext inside JS context

Can you explain more about what you did here?

**Comment by arthurgeron-work** [comment]
> Hi @arthurgeron-work,
> 
> 
> 
> I am investigating reports of this crash from other users still reporting this happening.
> 
> 
> 
> > Not call initWithContext inside JS context
> 
> 
> 
> Can you explain more about what you did here?

Sure! It seems there was some confusion in the documentation, which is now fixed. Before it'd suggest initializing  both natively on Android's "onCreate" with initWithContext(not sure why I said JS context before) as well from react-native. Turns out the correct way is to only initialize it in React Native once, anything else would cause issues.

**Comment by nan-li** [comment]
Thank you @arthurgeron-work

**Comment by chriscborg** [comment]
This issue is happening in native android as well. I have updated to the latest version of the SDK and the issue still isn't resolved. Please find the stack trace below. It seems to be ranging on different devices with different Android OS versions, however it's saying that 93% are in background state.

```
Caused by java.lang.NullPointerException:
       at com.onesignal.core.internal.application.impl.ApplicationService.getAppContext(ApplicationService.kt:40)
       at com.onesignal.core.internal.device.impl.DeviceService.packageInstalledAndEnabled(DeviceService.kt:106)
       at com.onesignal.core.internal.device.impl.DeviceService.isGMSInstalledAndEnabled(DeviceService.kt:101)
       at com.onesignal.core.internal.device.impl.DeviceService.supportsGooglePush(DeviceService.kt:84)
       at com.onesignal.core.internal.device.impl.DeviceService.getDeviceType(DeviceService.kt:41)
       at com.onesignal.core.internal.device.impl.DeviceService.isAndroidDeviceType(DeviceService.kt:18)
       at com.onesignal.location.LocationModule$register$1.invoke(LocationModule.kt:31)
       at com.onesignal.location.LocationModule$register$1.invoke(LocationModule.kt:28)
       at com.onesignal.common.services.ServiceRegistrationLambda.resolve(ServiceRegistration.kt:164)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:82)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:82)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceProvider.getService$com_onesignal_core(ServiceProvider.kt:39)
       at com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:235)
       at com.onesignal.OneSignal.initWithContext(OneSignal.kt:135)
       at com.myapp.MyApplication.configureOneSignal(MyApplication.kt:68)
       at com.myapp.MyApplication.onCreate(MyApplication.kt:33)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1162)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
       at android.app.ActivityThread.access$2000(ActivityThread.java:273)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

Crashing in this line of code called from the Application's onCreate function

```
    private fun configureOneSignal() {

        OneSignal.initWithContext(this, "xx-xx-xx-xx-xx")
        ...
    }
```

**Comment by uasghar-smile** [comment]
Hi @emawby @arthurgeron-work guys I am also getting this crash and I am not getting it only in "MOTO G" devices. I guess it persist almost in all android devices. Everything is working fine in development debug build. But when I am creating release .apk then I am getting this crash on app start in real devices as well as in android emulators (virtual devices). 

I am looking forward to get help on this. I am using latest version 5.0.6 of your lib.

```
Caused by java.lang.NullPointerException:
       at com.onesignal.core.internal.application.impl.ApplicationService.getAppContext(ApplicationService.kt:40)
       at com.onesignal.core.internal.device.impl.DeviceService.packageInstalledAndEnabled(DeviceService.kt:106)
       at com.onesignal.core.internal.device.impl.DeviceService.isGMSInstalledAndEnabled(DeviceService.kt:101)
       at com.onesignal.core.internal.device.impl.DeviceService.supportsGooglePush(DeviceService.kt:84)
       at com.onesignal.core.internal.device.impl.DeviceService.getDeviceType(DeviceService.kt:41)
       at com.onesignal.core.internal.device.impl.DeviceService.isAndroidDeviceType(DeviceService.kt:18)
       at com.onesignal.location.LocationModule$register$1.invoke(LocationModule.kt:31)
       at com.onesignal.location.LocationModule$register$1.invoke(LocationModule.kt:28)
       at com.onesignal.common.services.ServiceRegistrationLambda.resolve(ServiceRegistration.kt:164)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:82)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:82)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceProvider.getService$com_onesignal_core(ServiceProvider.kt:39)
       at com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:235)
       at com.onesignal.OneSignal.initWithContext(OneSignal.kt:135)
       at com.myapp.MyApplication.configureOneSignal(MyApplication.kt:68)
       at com.myapp.MyApplication.onCreate(MyApplication.kt:33)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1162)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
       at android.app.ActivityThread.access$2000(ActivityThread.java:273)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by jkasten2** [comment]
[Release 5.1.0](https://github.com/OneSignal/react-native-onesignal/releases/tag/5.1.0) has a fix in it's included [OneSignal-Android-SDK 5.1.6](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.6) that addresses this issue. Please update and let us know if it solves the issue for you. Please provide the new stack trace if it does not.

**Comment by uasghar-smile** [comment]
Hi @jkasten2 thanks for your reply. I tried to upgrade my version from `5.0.6` to `5.1.0`. But my android release .apk is still crashing on app launch after install.

Here are the logs

```
03-20 14:24:43.111 18071 18177 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
03-20 14:24:43.111 18071 18177 E AndroidRuntime: Process: com.smile.members, PID: 18071
03-20 14:24:43.111 18071 18177 E AndroidRuntime: java.lang.RuntimeException: Could not invoke OneSignal.addTriggers
03-20 14:24:43.111 18071 18177 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
03-20 14:24:43.111 18071 18177 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
03-20 14:24:43.111 18071 18177 E AndroidRuntime: 	at com.facebook.jni.NativeRunnable.run(Native Method)
03-20 14:24:43.111 18071 18177 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
03-20 14:24:43.111 18071 18177 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-20 14:24:43.111 18071 18177 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
03-20 14:24:43.111 18071 18177 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
03-20 14:24:43.111 18071 18177 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
03-20 14:24:43.111 18071 18177 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
03-20 14:24:43.111 18071 18177 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
03-20 14:24:43.111 18071 18177 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
03-20 14:24:43.111 18071 18177 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-20 14:24:43.111 18071 18177 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
03-20 14:24:43.111 18071 18177 E AndroidRuntime: 	... 9 more
03-20 14:24:43.111 18071 18177 E AndroidRuntime: Caused by: java.lang.Exception: Must call 'initWithContext' before use
03-20 14:24:43.111 18071 18177 E AndroidRuntime: 	at com.onesignal.internal.OneSignalImp.getInAppMessages(OneSignalImp.kt:112)
03-20 14:24:43.111 18071 18177 E AndroidRuntime: 	at com.onesignal.OneSignal.getInAppMessages(OneSignal.kt:78)
03-20 14:24:43.111 18071 18177 E AndroidRuntime: 	at com.onesignal.rnonesignalandroid.RNOneSignal.addTriggers(RNOneSignal.java:307)
03-20 14:24:43.111 18071 18177 E AndroidRuntime: 	... 11 more
03-20 14:24:44.663   565   661 W ActivityTaskManager:   Force finishing activity com.smile.members/.MainActivity
03-20 14:24:44.673   565   591 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
03-20 14:24:44.673   565   591 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
03-20 14:24:44.688   565  3090 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
03-20 14:24:44.688   565  3090 W OpenGLRenderer: Failed to initialize 101010-2 format, error = EGL_SUCCESS
03-20 14:24:44.705   565  1040 W InputManager-JNI: Input channel object 'afcaccb com.smile.members/com.smile.members.MainActivity (client)' was disposed without first being removed with the input manager!
03-20 14:24:44.753   565   584 W WindowManager: Failed to deliver inset state change to w=Window{afcaccb u0 com.smile.members/com.smile.members.MainActivity EXITING}
03-20 14:24:44.753   565   584 W WindowManager: android.os.DeadObjectException
03-20 14:24:44.753   565   584 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
03-20 14:24:44.753   565   584 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
03-20 14:24:44.753   565   584 W WindowManager: 	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:473)
03-20 14:24:44.753   565   584 W WindowManager: 	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3995)
03-20 14:24:44.753   565   584 W WindowManager: 	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$4(InsetsStateController.java:351)
03-20 14:24:44.753   565   584 W WindowManager: 	at com.android.server.wm.InsetsStateController.$r8$lambda$An2IoiA3BeA5IWc6QwBOjKArM80(Unknown Source:0)
03-20 14:24:44.753   565   584 W WindowManager: 	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda3.run(Unknown Source:2)
03-20 14:24:44.753   565   584 W WindowManager: 	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:345)
03-20 14:24:44.753   565   584 W WindowManager: 	at com.android.server.wm.WindowAnimator.animate(WindowAnimator.java:226)
03-20 14:24:44.753   565   584 W WindowManager: 	at com.android.server.wm.WindowAnimator.lambda$new$1(WindowAnimator.java:106)
03-20 14:24:44.753   565   584 W WindowManager: 	at com.android.server.wm.WindowAnimator.$r8$lambda$fo2Nk5bb9hY3lvmHsTnTEwtZMbI(Unknown Source:0)
03-20 14:24:44.753   565   584 W WindowManager: 	at com.android.server.wm.WindowAnimator$$ExternalSyntheticLambda1.doFrame(Unknown Source:2)
03-20 14:24:44.753   565   584 W WindowManager: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
03-20 14:24:44.753   565   584 W WindowManager: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
03-20 14:24:44.753   565   584 W WindowManager: 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
03-20 14:24:44.753   565   584 W WindowManager: 	at android.view.Choreographer.doFrame(Choreographer.java:827)
03-20 14:24:44.753   565   584 W WindowManager: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
03-20 14:24:44.753   565   584 W WindowManager: 	at android.os.Handler.handleCallback(Handler.java:942)
03-20 14:24:44.753   565   584 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-20 14:24:44.753   565   584 W WindowManager: 	at android.os.Looper.loopOnce(Looper.java:201)
03-20 14:24:44.753   565   584 W WindowManager: 	at android.os.Looper.loop(Looper.java:288)
03-20 14:24:44.753   565   584 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
03-20 14:24:44.753   565   584 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
03-20 14:24:44.757  1036  1036 E BcSmartspaceCard: No tap action can be set up
03-20 14:24:44.771   565   584 W WindowManager: Exception thrown during dispatchAppVisibility Window{afcaccb u0 com.smile.members/com.smile.members.MainActivity EXITING}
03-20 14:24:44.771   565   584 W WindowManager: android.os.DeadObjectException
03-20 14:24:44.771   565   584 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
03-20 14:24:44.771   565   584 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
03-20 14:24:44.771   565   584 W WindowManager: 	at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:536)
03-20 14:24:44.771   565   584 W WindowManager: 	at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:3469)
03-20 14:24:44.771   565   584 W WindowManager: 	at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1225)
03-20 14:24:44.771   565   584 W WindowManager: 	at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:392)
03-20 14:24:44.771   565   584 W WindowManager: 	at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:6714)
03-20 14:24:44.771   565   584 W WindowManager: 	at com.android.server.wm.ActivityRecord.onAnimationFinished(ActivityRecord.java:7526)
03-20 14:24:44.771   565   584 W WindowManager: 	at com.android.server.wm.ActivityRecord.postApplyAnimation(ActivityRecord.java:5405)
03-20 14:24:44.771   565   584 W WindowManager: 	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5364)
03-20 14:24:44.771   565   584 W WindowManager: 	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5368)
03-20 14:24:44.771   565   584 W WindowManager: 	at com.android.server.wm.AppTransitionController.handleClosingApps(AppTransitionController.java:1144)
03-20 14:24:44.771   565   584 W WindowManager: 	at com.android.server.wm.AppTransitionController.handleAppTransitionReady(AppTransitionController.java:292)
03-20 14:24:44.771   565   584 W WindowManager: 	at com.android.server.wm.RootWindowContainer.checkAppTransitionReady(RootWindowContainer.java:970)
03-20 14:24:44.771   565   584 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:834)
03-20 14:24:44.771   565   584 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:777)
03-20 14:24:44.771   565   584 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:177)
03-20 14:24:44.771   565   584 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:126)
03-20 14:24:44.771   565   584 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:115)
03-20 14:24:44.771   565   584 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer$Traverser.run(WindowSurfacePlacer.java:57)
03-20 14:24:44.771   565   584 W WindowManager: 	at android.os.Handler.handleCallback(Handler.java:942)
03-20 14:24:44.771   565   584 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-20 14:24:44.771   565   584 W WindowManager: 	at android.os.Looper.loopOnce(Looper.java:201)
03-20 14:24:44.771   565   584 W WindowManager: 	at android.os.Looper.loop(Looper.java:288)
03-20 14:24:44.771   565   584 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
03-20 14:24:44.771   565   584 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
```

<img width="1268" alt="Screenshot 2024-03-20 at 2 25 29 PM" src="https://github.com/OneSignal/react-native-onesignal/assets/102786004/e63f77ef-915f-47cd-9734-d1e619b6b5a8">

**Comment by uasghar-smile** [comment]
Anyone faced this issue or able to fixed that?

**Comment by chriscborg** [comment]
This issue seems to be resolved with the latest version from my end.

**Comment by uasghar-smile** [comment]
@chriscborg  I tried but it doesn't helps me

**Comment by mreram** [comment]
Same issue on 5.1.6

**Comment by RahulSocialDev** [comment]
I am using react native OneSignal version 5.2.2. The issue is not there in development but in production mode.

My code in hook which is inializing the onesignal
```tsx
useEffect(() => {
    const initialiseOnesignal = async () => {
      // Remove this method to stop OneSignal Debugging
      OneSignal.Debug.setLogLevel(LogLevel.Verbose);
      // OneSignal Initialization
      OneSignal.initialize(Config.ONESIGNAL_APP_ID);

      OneSignal.Notifications.requestPermission(true);

      OneSignal.User.pushSubscription.addEventListener('change', async _ => {
        // const oneSignalId = await OneSignal.User.getOnesignalId();
      
      });
    };
   initialiseOnesignal();
  }, []);
```
Here is the stack trace
```
Exception in native call
java.lang.RuntimeException: Could not invoke OneSignal.addPermissionObserver
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:381)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:149)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:149) 
	at com.facebook.jni.NativeRunnable.run(Native Method) 
	at android.os.Handler.handleCallback(Handler.java:958) 
	at android.os.Handler.dispatchMessage(Handler.java:99) 
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
	at android.os.Looper.loopOnce(Looper.java:205) 
	at android.os.Looper.loop(Looper.java:294) 
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234) 
	at java.lang.Thread.run(Thread.java:1012) 
Caused by: java.lang.Exception: Must call 'initWithContext' before use
	at com.onesignal.internal.OneSignalImp.getNotifications(OneSignalImp.kt:96)
	at com.onesignal.OneSignal.getNotifications(OneSignal.kt:62)
	at com.onesignal.rnonesignalandroid.RNOneSignal.addPermissionObserver(RNOneSignal.java:418)
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:149) 
	at com.facebook.jni.NativeRunnable.run(Native Method) 
	at android.os.Handler.handleCallback(Handler.java:958) 
	at android.os.Handler.dispatchMessage(Handler.java:99) 
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
	at android.os.Looper.loopOnce(Looper.java:205) 
	at android.os.Looper.loop(Looper.java:294) 
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234) 
	at java.lang.Thread.run(Thread.java:1012) 
```

**Comment by jennantilla** [comment]
Hello everyone--since the last activity in this issue, we have made several improvements to our SDK. Please update to the [latest version](https://github.com/OneSignal/react-native-onesignal/releases/tag/5.2.7) and let us know if you are still experiencing this problem.

Thank you!

**Comment by nan-li** [comment]
Hi everyone, we haven't heard any updates since the last post above.

Closing out this issue but please reach out if you are seeing any further problems.
