### ISSUE TITLE
Error - RNOneSignal.configure

### ISSUE THREAD

**Issue by devgenerate** [OneSignal/react-native-onesignal#208]
Hello, I configured my app for Android and worked great, after I added configuration for iOS (on one signal) but after I did all according to instructions I get next message: '  undefined is not an object (evaluating RNOneSignal.configure)' and really I don´t know what is the problem.

```** BUILD FAILED **

The following build commands failed:

	CompileC /Users/XXX/Documents/Code/XXX/XXX/ios/build/Build/Intermediates/RCTFBSDK.build/Debug-iphonesimulator/RCTFBSDK.build/Objects-normal/x86_64/RCTFBSDKAppEvents.o RCTFBSDK/core/RCTFBSDKAppEvents.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/XXX.app
An error was encountered processing the command (domain=MIInstallerErrorDomain, code=4):
Failed to chmod /Users/XXX/Library/Developer/CoreSimulator/Devices/156CE97C-D171-463F-B811-F550730E70C5/data/Library/Caches/com.apple.containermanagerd/Bundle/Application/F31DE11F-6351-4EF0-9DA7-81526F562A4E/XXX.app/XXX : No such file or directory
Launching com.XXX.XXX
com.XXX.XXX: 17573
```

**Comment by GustavoHGS** [comment]
After installed the lastest version of react-native-onesignal, I had to react-native unlink react-native-onesignal and link it again with react-native link react-native-onesignal
It worked for me.

**Comment by devgenerate** [comment]
@GustavoHGS Thanks, I did it and worked for me.

**Comment by jkasten2** [comment]
@davidgit75 @avishayil Looks like this is solved. Can we close this issue?

**Comment by dzpt** [comment]
@GustavoHGS i get this error and after relink the lib, the error is still there.

**Comment by rafaelviny** [comment]
What version are you using?
I have problem in IOS using react-native-onesignal: 3.0.3

I initially installed 3.0.5, the error occurred, downgraded to 3.0.3, unlinked and linked, but without success
