### ISSUE TITLE
Update to OneSignal iOS SDK v2.10.2 to remove UIWebView

### ISSUE THREAD

**Issue by ianmcgregor** [OneSignal/react-native-onesignal#841]
**Description:**

Apple will stop accepting submissions of apps that use UIWebView APIs.

OneSignal iOS SDK has now switched to WKWebView from the deprecated UIWebView to resolve this issue.

**Environment**

React Native 0.60.x

**Steps to Reproduce Issue:**

Submit app containing react-native-onesignal and receive an email from Apple complaining about the use of UIWebView!

**Anything else:**

(crash stacktraces, as well as any other information here)

Corresponding issue on OneSignal-iOS-SDK repo: https://github.com/OneSignal/OneSignal-iOS-SDK/issues/522

**Comment by MaxInMoon** [comment]
Hi!

We receive this email "URGENT & IMPORT iOS 13 Update Changes", but does this repo already has a new release to fix that?

**Comment by rgomezp** [comment]
This has been fixed. Please update to the latest version of the SDK

**Comment by cinder92** [comment]
@rgomezp could you please share the link of latest SDK and how to install it? im using `react-native-onesignal 3.4.2` and still receiving that warning

**Comment by ianmcgregor** [comment]
@cinder92 make sure you do `cd ios && pod update` to update the native part
