### ISSUE TITLE
Invariant Violation: NetInfo has been removed from React Native (RN 0.61.2)

### ISSUE THREAD

**Issue by bkraeling** [OneSignal/react-native-onesignal#889]
**Description:**
NetInfo imported from `react-native` is deprecated and causes an error in React Native 0.61.2.

**Environment**
OneSignal SDK version: 3.4.2
Installed via npm
React Native version: 0.61.2

**Steps to Reproduce Issue:**
1. Use RN 0.61.2 and OneSignal 3.4.2
2. App does not load

**Anything else:**

I believe merging #876 should fix this issue. 

<img width="502" alt="Screen Shot 2019-10-24 at 10 39 47 AM" src="https://user-images.githubusercontent.com/6200068/67496944-35f8f900-f64b-11e9-9461-28bfcf080c89.png">

**Comment by rgomezp** [comment]
This has been resolved in 3.5.0

**Comment by ShaneMatthias** [comment]
Anyone have this issue still? I have checked all my import statements, and all my import statements for my dependencies and none of them are importing using the old way. Yet, I still get this error.

React-Native: 0.61
@react-native-community/netinfo: ^5.3.3
