### ISSUE TITLE
OneSignalPrefs$WritePrefHandlerThread.startDelayedWrite crash on Android

### ISSUE THREAD

**Issue by Rodrigo77777** [OneSignal/react-native-onesignal#944]
**Description:**

This seems to be an issue with the Android SDK as it has been reported below as well:

https://github.com/OneSignal/OneSignal-Android-SDK/issues/917

App is just crashing in production, mainly on Android 9 as far as I can tell. The stack trace is further below

I'm not sure if this package has a dependency on the Android SDK in the link above, but thought it better to make you aware of this issue in either case.

**Environment**
React Native version 0.61.5
One Signal installed through npm

**Steps to Reproduce Issue:**
Unsure, haven't been able to reproduce in development, but has happened more than once in production

**Anything else:**

`Caused by: java.lang.IllegalThreadStateException: 
  at java.lang.Thread.start (Thread.java:724)
  at com.onesignal.OneSignalPrefs$WritePrefHandlerThread.startDelayedWrite (OneSignalPrefs.java:117)
  at com.onesignal.OneSignalPrefs.startDelayedWrite (OneSignalPrefs.java:183)
  at com.onesignal.OneSignal.setAppContext (OneSignal.java:601)
  at com.onesignal.OneSignalSyncServiceUtils.doBackgroundSync (OneSignalSyncServiceUtils.java:175)
  at com.onesignal.SyncJobService.onStartJob (SyncJobService.java:40)
  at android.app.job.JobService$1.onStartJob (JobService.java:62)
  at android.app.job.JobServiceEngine$JobHandler.handleMessage (JobServiceEngine.java:108)`

**Comment by rgomezp** [comment]
Thanks for reporting this issue. Please follow the issue in the Android native repository as it applies to all Android implementations

**Comment by Rodrigo77777** [comment]
Yeah it seems like there's already a fix, but it doesn't seem to be something I can add manually until the next update is released. Will we have to wait for a release from that package and then this one to get the issue fixed? Thanks!

**Comment by rgomezp** [comment]
The release should be out later today

**Comment by shefich** [comment]
Hello, Where is the release?
It's a pity, but I couldn't remake classes .jar file, so I need the updated plugin.
Thank you in advance.

**Comment by rgomezp** [comment]
Howdy @shefich ,
We weren't able to ship the release as some other issues arose. We hope to get this released as soon as possible. Cheers

**Comment by shefich** [comment]
Hello,

I updated plugin, but still have error. It looks like it is the same error, but better take a look, please:


**OneSignalPrefs.java line 117
com.onesignal.OneSignalPrefs$WritePrefHandlerThread.startDelayedWrite

Fatal Exception: java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2018.4.13f1
Device model      : samsung SM-A307FN
Device fingerprint: samsung/a30sxx/a30s:9/PPR1.180610.011/A307FNXXU1ASI1:user/release-keys

Caused by java.lang.RuntimeException: java.lang.IllegalThreadStateException
       at android.app.job.JobServiceEngine$JobHandler.handleMessage + 112(JobServiceEngine.java:112)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 216(Looper.java:216)
       at android.app.ActivityThread.main + 7285(ActivityThread.java:7285)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 494(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main + 975(ZygoteInit.java:975)

Caused by java.lang.IllegalThreadStateException
       at java.lang.Thread.start + 724(Thread.java:724)
       at com.onesignal.OneSignalPrefs$WritePrefHandlerThread.startDelayedWrite + 117(OneSignalPrefs.java:117)
       at com.onesignal.OneSignalPrefs.startDelayedWrite + 183(OneSignalPrefs.java:183)
       at com.onesignal.OneSignal.setAppContext + 601(OneSignal.java:601)
       at com.onesignal.OneSignalSyncServiceUtils.doBackgroundSync + 175(OneSignalSyncServiceUtils.java:175)
       at com.onesignal.SyncJobService.onStartJob + 40(SyncJobService.java:40)
       at android.app.job.JobService$1.onStartJob + 62(JobService.java:62)
       at android.app.job.JobServiceEngine$JobHandler.handleMessage + 108(JobServiceEngine.java:108)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 216(Looper.java:216)
       at android.app.ActivityThread.main + 7285(ActivityThread.java:7285)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 494(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main + 975(ZygoteInit.java:975)**

**Comment by Rodrigo77777** [comment]
Same here, already reported on the Android native repository https://github.com/OneSignal/OneSignal-Android-SDK/issues/917 but haven't had an answer so far

**Comment by rgomezp** [comment]
Sorry this didn't resolve the issue, please track the issue here: https://github.com/OneSignal/OneSignal-Android-SDK/issues/917

**Comment by timfantasia** [comment]
Hi @rgomezp,
Same issue here. I will keep waiting for an answer. Thanks for the support.

**Comment by maitycyrus** [comment]
Same here
