### ISSUE TITLE
No known class method for selector 'setExternalUserId:withCompletion:'

### ISSUE THREAD

**Issue by luutruong** [OneSignal/react-native-onesignal#969]
**Description:**

```
XXX/react-native-onesignal/ios/RCTOneSignal/RCTOneSignalEventEmitter.m:342:16: No known class method for selector 'setExternalUserId:withCompletion:'
```

* react-native-onesignal@3.7.0
* OneSignal@2.13.0

**Comment by kian92** [comment]
Yes, I have same error as well for iOS & Android

**Comment by rochapablo** [comment]
Same here. The project was working (for a long time), today I had to make some changes and can't even run it. 

```
node_modules/react-native-onesignal/ios/RCTOneSignal/RCTOneSignalEventEmitter.m:342:16: No known class method for selector 'setExternalUserId:withCompletion:'
```

```
node_modules/react-native-onesignal/ios/RCTOneSignal/RCTOneSignalEventEmitter.m:355:16: No known class method for selector 'removeExternalUserId:'
```

```
"react": "16.12.0",
"react-native": "0.61.5",
"react-native-onesignal": "^3.6.3" / "^3.7.0",
```

**Comment by sjaloomconnect** [comment]
I have the same issue, 

    no known class method for selector 'setExternalUserId:withCompletion:'
    no known class method for selector 'removeExternalUserId:'

Just updated to:

"react": "16.13.1",
"react-native": "0.62.0",
"react-native-onesignal": "^3.7.0",

**Comment by felix-voicehub** [comment]
Can confirm. Builds on Bitrise are failing, both iOS and Android.

**Comment by fritzfr** [comment]
Seems to be a broken release.
I fixed this by pinning the versions:

Podfile:
```
target 'OneSignalNotificationServiceExtension' do
	pod 'OneSignal', '2.12.6'
end
```

package.json
```
"react-native-onesignal": "3.6.4",
```

Works again.

**Comment by erickhdzreyes** [comment]
> Seems to be a broken release.
> I fixed this by pinning the versions:
> 
> Podfile:
> 
> ```
> target 'OneSignalNotificationServiceExtension' do
> 	pod 'OneSignal', '2.12.6'
> end
> ```
> 
> package.json
> 
> ```
> "react-native-onesignal": "3.6.4",
> ```
> 
> Works again.

That's worked forme, thanks!
react-native: 0.61.5

**Comment by jkasten2** [comment]
This is now fixed in the 3.7.1 release.
https://github.com/OneSignal/react-native-onesignal/releases/tag/3.7.1

**Comment by sjaloomconnect** [comment]
Seems to be working for me too. Thanks for fixing it.

**Comment by hugoh59** [comment]
Still getting error after upgraded to 3.7.1 but worked with 3.6.4.

**Comment by Eth3rnit3** [comment]
I had the same error then I replaced `platform :ios, '9.0'` by `platform :ios, '11.0'` and I have no more error, so there is a chance that it depends on the desired target.

**Comment by abdullahizzuddiin** [comment]
I just upgraded to `"version": "3.8.1"`, and I got this error. Anyone has solution?
